#!/usr/bin/env python3
"""
copy_scaling.py - ICEC Protocol Copy Requirements Analysis
===========================================================

Derives the exact copy scaling from Shiraishi-Takagi (PRL 132, 180202, 2024)
Supplemental Material, and computes requirements for the 4 benchmark algorithms.

Theory (from Supplemental Material, proof of Theorem S.10):
═══════════════════════════════════════════════════════════

LAYER 1: Catalyst Preparation (Lemma S.16 → S.17)
  For each 2-level catalyst c_i, need μ_i copies of ρ:
    ρ^{⊗μ_i} → c_i  (exact, by covariant operation)

  μ_i depends on the coherence cost:
    1/R(|+><+| → c_i) ~ QFI(c_i) / QFI(|+><+|)

  Since c_i is a full-rank qubit state with D(c_i) ⊆ D(ρ),
  and the protocol goes:
    ρ^{⊗m} → weakly coherent qubit η  (Lemma S.16, m copies)
    η^{⊗m'} → |+><+|                  (Ref [53], m' copies)
    |+><+|^{⊗k'} → c_i               (Lemma S.14, k' copies)

  Total per catalyst: μ_i = m · m' · k'

  Key bounds:
    m: depends on min nonzero |ρ_{ij}| for matching mode
       m ~ 1/|ρ_{ij}|^2 for the weakest coherent mode  [Ref 45, Lemma 11]
    m': fixed constant ~O(1) since η has nonzero coherence
    k': depends on QFI ratio, bounded by O(QFI(c_i)/QFI(|+>))

  In practice: μ_i ~ C / |ρ_{ij,min}|^2 where C is a constant

  Total: μ = Σ_{i=1}^N μ_i

LAYER 2: Marginal-Catalytic Amplification (Lemma S.13)
  Given N^k sets of catalysts c^{⊗N^k}:
    Can realize (k+1)·N^k marginal-catalytic transformations

LAYER 3: Correlated-Catalytic Conversion (Prop S.23)
  Converts asymptotic protocol to single-shot correlated-catalytic:
    Uses n copies of ρ → 1 copy of σ ≈ ρ' + catalyst c (unchanged)

FULL PROTOCOL:
  Input copies:   n = μ · N^k
  Output copies:  m = (k+1) · N^k
  Rate:           R = m/n = (k+1)/μ → ∞ as k → ∞

  where:
    N = number of 2-level catalysts (depends on target dimension d')
    μ = total copies for catalyst preparation
    k = amplification rounds (free parameter, controls rate)

For the CORRELATED-CATALYTIC transformation (Theorem S.24):
  Uses Prop S.23 with n copies from the asymptotic protocol.
  Catalyst dimension: dim(c) = n · dim(ρ) · dim(register)
                             = n · d · n  (Eq. 34)
"""

import numpy as np
from math import ceil, sqrt, log2, pi, log
from typing import Dict, List, Tuple
import sys

sys.path.insert(0, '/Users/deeptell01/Documents/alterego/personal/cqec')
from core import (
    coherence_l1, quantum_fisher_information,
    modes_of_asymmetry, resonant_coherent_modes,
    EnergySystem, maximally_coherent_state,
)


# ============================================================
# Core Scaling Functions
# ============================================================

def count_nonzero_offdiag_pairs(rho: np.ndarray, tol: float = 1e-15) -> int:
    """Count number of distinct off-diagonal pairs (i,j) with i<j and |ρ_{ij}| > tol.
    This determines N (number of 2-level catalysts needed) for the target state.
    """
    d = rho.shape[0]
    count = 0
    for i in range(d):
        for j in range(i + 1, d):
            if abs(rho[i, j]) > tol:
                count += 1
    return count


def count_distinct_modes(rho: np.ndarray, energies: np.ndarray, tol: float = 1e-10) -> int:
    """Count distinct energy gaps Δ_{ij} with nonzero coherence.
    This is |D(ρ)|, the set of modes of asymmetry.
    """
    modes = modes_of_asymmetry(rho, energies, tol)
    return len(modes)


def min_nonzero_coherence(rho: np.ndarray, tol: float = 1e-15) -> float:
    """Find minimum nonzero off-diagonal element magnitude."""
    d = rho.shape[0]
    min_val = float('inf')
    for i in range(d):
        for j in range(d):
            if i != j and abs(rho[i, j]) > tol:
                min_val = min(min_val, abs(rho[i, j]))
    return min_val if min_val < float('inf') else 0.0


def compute_N_catalysts(rho_target: np.ndarray, energies: np.ndarray) -> int:
    """Compute N: number of 2-level catalytic systems needed.

    From Lemma S.12 (Theorem 2 in Ref [45]):
    For any two quantum states ξ and ρ', and for any accuracy ε > 0,
    there exists a set of two-level catalytic systems C_1,...,C_N
    with full-rank qubit mixed states c_1,...,c_N and a covariant operation Λ.

    N is determined by the number of distinct coherent modes in ρ'.
    Specifically, each mode Δ ∈ D(ρ') requires at least one 2-level catalyst
    with matching energy gap, but modes can share catalysts if they
    are integer multiples.

    Conservative bound: N = |D(ρ')| (number of distinct modes)
    Tight bound: N = rank of D(ρ') as a Z-module
    """
    modes = modes_of_asymmetry(rho_target, energies)
    if not modes:
        return 0

    # Find the rank of the Z-module generated by the modes
    # This equals the number of rationally independent generators
    mode_list = sorted(modes)

    # Simple approach: count rationally independent modes
    independent = []
    for m in mode_list:
        if abs(m) < 1e-10:
            continue
        is_dependent = False
        for ind in independent:
            if abs(ind) < 1e-10:
                continue
            ratio = m / ind
            # Check if ratio is a rational number p/q with small p,q
            for q in range(1, 20):
                p = round(ratio * q)
                if abs(ratio * q - p) < 1e-8:
                    is_dependent = True
                    break
            if is_dependent:
                break
        if not is_dependent:
            independent.append(m)

    return max(len(independent), 1)


def compute_mu_per_catalyst(rho_source: np.ndarray, energies: np.ndarray,
                             noise_strength: float = 0.0) -> float:
    """Compute μ_i: copies of ρ needed to prepare one 2-level catalyst.

    From the proof chain (Lemma S.16 → S.17):

    Step 1 (Lemma S.16): ρ^{⊗m} → weakly coherent qubit state η
      - Requires: D(η) ⊆ D(ρ)
      - Copy count m: depends on the protocol in Ref [45, Lemma 11]
      - Scaling: m ~ O(1/|ρ_{ij}|²) for the matching mode
        (need to extract coherence from weak off-diagonal elements)

    Step 2 (Ref [53], Cirac-Ekert-Macchiavello 1999):
      η^{⊗m'} → one copy of |+><+| (maximally coherent qubit)
      - m' ~ 1/C_l1(η)² (inverse square of L1 coherence of η)
      - But η already has nonzero coherence, so m' = O(1)

    Step 3 (exact preparation via Lemma S.14):
      |+><+|^{⊗k'} → c_i (target full-rank qubit catalyst)
      - k' = O(1) since |+> is maximally coherent among qubits
      - The coherence cost 1/R(|+><+| → c_i) = QFI(c_i)/QFI(|+><+|) ≤ 1

    Combined: μ_i = m · m' · k'

    For practical computation:
      If ρ has been affected by dephasing with parameter γ:
        |ρ_{ij}| ~ |ρ^{ideal}_{ij}| · exp(-γ)
        m ~ 1/exp(-2γ) = exp(2γ)

      If ρ has been affected by depolarizing noise p:
        |ρ_{ij}| ~ (1-p)|ρ^{ideal}_{ij}|
        m ~ 1/(1-p)²
    """
    d = rho_source.shape[0]

    # Find minimum nonzero coherence (bottleneck mode)
    min_coh = min_nonzero_coherence(rho_source)

    if min_coh <= 0:
        return float('inf')  # Cannot prepare catalyst

    # Step 1: copies to extract one weakly coherent qubit
    # From Ref [45], Lemma 11: The protocol uses O(1/|ρ_{ij}|²) copies
    # to produce a state with coherence on the matching mode
    m = ceil(1.0 / (min_coh ** 2))

    # Step 2: copies to amplify weak coherence to max coherence
    # From Cirac-Ekert-Macchiavello (PRL 82, 4344, 1999):
    # Need ~1/C² copies of a state with coherence C to get |+>
    # But after Step 1, we have coherence ~min_coh * sqrt(m) ~ 1
    # so m' ~ O(1)
    m_prime = 1  # Constant factor

    # Step 3: convert |+> to target catalyst
    # Since |+> is maximally coherent, k' = O(1)
    k_prime = 1

    # Total copies per catalyst
    mu_i = m * m_prime * k_prime

    return mu_i


def compute_full_copy_requirements(
    d: int,
    rho_source: np.ndarray,
    rho_target: np.ndarray,
    energies: np.ndarray,
    k: int = 1,
    epsilon: float = 0.01,
) -> Dict:
    """Compute full copy requirements for ICEC protocol.

    Args:
        d: Hilbert space dimension (2^n_qubits)
        rho_source: noisy source state
        rho_target: ideal target state
        energies: energy eigenvalues
        k: amplification rounds (controls rate)
        epsilon: target accuracy

    Returns:
        Dictionary with all scaling parameters
    """
    # N: number of 2-level catalysts
    N = compute_N_catalysts(rho_target, energies)

    # μ_i per catalyst
    mu_per = compute_mu_per_catalyst(rho_source, energies)

    # Total μ = N · μ_per (conservative: each catalyst costs the same)
    mu_total = N * mu_per

    # Input copies: n = μ · N^k
    n_input = mu_total * (N ** k) if N > 0 else mu_total

    # Output copies: m = (k+1) · N^k
    m_output = (k + 1) * (N ** k) if N > 0 else (k + 1)

    # Rate
    rate = m_output / n_input if n_input > 0 else 0

    # Catalyst dimension (from Eq. 34 of Prop S.23)
    # c = (1/n) Σ_{k=1}^n ρ^{⊗(k-1)} ⊗ τ_{n-k} ⊗ |k><k|_R
    # dim(c) = d^{n-1} · d · n (system copies × remainder × register)
    # In practice, use the asymptotic n from the protocol
    n_for_catalyst = max(int(mu_total), 2)
    catalyst_dim_log2 = (n_for_catalyst - 1) * log2(d) + log2(d) + log2(n_for_catalyst)

    # Total qubits for the full protocol
    # System: n_qubits = log2(d)
    # Catalysts: N qubits (each 2-level)
    # Ancillas for covariant operation: O(N) qubits
    n_system_qubits = int(ceil(log2(d)))
    n_catalyst_qubits = N  # Each catalyst is 2-level (1 qubit)
    n_ancilla_qubits = N   # Ancillas for EC gates
    total_qubits = n_system_qubits + n_catalyst_qubits + n_ancilla_qubits

    # Coherence metrics
    coh_source = coherence_l1(rho_source, energies)
    coh_target = coherence_l1(rho_target, energies)
    min_coh = min_nonzero_coherence(rho_source)

    return {
        'dimension': d,
        'n_system_qubits': n_system_qubits,
        'N_catalysts': N,
        'mu_per_catalyst': mu_per,
        'mu_total': mu_total,
        'k_rounds': k,
        'n_input_copies': n_input,
        'm_output_copies': m_output,
        'rate': rate,
        'total_operational_qubits': total_qubits,
        'n_catalyst_qubits': n_catalyst_qubits,
        'catalyst_dim_log2': catalyst_dim_log2,
        'coh_source_l1': coh_source,
        'coh_target_l1': coh_target,
        'min_nonzero_coherence': min_coh,
    }


# ============================================================
# Noise Models
# ============================================================

def apply_dephasing(rho, gamma):
    d = rho.shape[0]
    result = rho.copy()
    for i in range(d):
        for j in range(d):
            if i != j:
                result[i, j] *= np.exp(-gamma)
    return result

def apply_depolarizing(rho, p):
    d = rho.shape[0]
    return (1 - p) * rho + p * np.eye(d, dtype=complex) / d

def apply_amplitude_damping(rho, gamma):
    d = rho.shape[0]
    result = rho.copy()
    for i in range(d):
        for j in range(d):
            if i != j:
                result[i, j] *= np.sqrt(1 - gamma)
    # Shift populations
    result[0, 0] += gamma * (1 - result[0, 0].real)
    for i in range(1, d):
        result[i, i] *= (1 - gamma)
    result /= np.trace(result)
    return result


# ============================================================
# Main Analysis
# ============================================================

def analyze_algorithm(name: str, n_qubits: int, rho_ideal: np.ndarray,
                      noise_configs: List[Dict]) -> List[Dict]:
    """Analyze copy requirements for one algorithm under various noise levels."""
    d = 2**n_qubits
    energies = np.arange(d, dtype=float)
    results = []

    for noise in noise_configs:
        rho_noisy = rho_ideal.copy()
        if noise.get('dephasing', 0) > 0:
            rho_noisy = apply_dephasing(rho_noisy, noise['dephasing'])
        if noise.get('depol', 0) > 0:
            rho_noisy = apply_depolarizing(rho_noisy, noise['depol'])
        if noise.get('amp_damp', 0) > 0:
            rho_noisy = apply_amplitude_damping(rho_noisy, noise['amp_damp'])

        rho_noisy = (rho_noisy + rho_noisy.conj().T) / 2
        rho_noisy /= np.trace(rho_noisy)

        for k in [1, 3, 5, 10]:
            req = compute_full_copy_requirements(
                d, rho_noisy, rho_ideal, energies, k=k
            )
            req['algorithm'] = name
            req['noise_name'] = noise['name']
            req['noise_params'] = noise
            results.append(req)

    return results


def make_ideal_state(n_qubits: int, state_type: str = 'plus') -> np.ndarray:
    """Create ideal state for analysis."""
    d = 2**n_qubits
    if state_type == 'plus':
        psi = np.ones(d, dtype=complex) / np.sqrt(d)
    elif state_type == 'ghz':
        psi = np.zeros(d, dtype=complex)
        psi[0] = 1.0 / np.sqrt(2)
        psi[-1] = 1.0 / np.sqrt(2)
    elif state_type == 'random':
        psi = np.random.randn(d) + 1j * np.random.randn(d)
        psi /= np.linalg.norm(psi)
    else:
        psi = np.ones(d, dtype=complex) / np.sqrt(d)
    return np.outer(psi, psi.conj())


def run_full_analysis():
    """Run comprehensive copy scaling analysis."""

    print("=" * 90)
    print("ICEC COPY SCALING ANALYSIS")
    print("量子ビット数 vs 必要コピー数 (Shiraishi-Takagi理論)")
    print("=" * 90)

    # ──────────────────────────────────────────────────
    # Part 1: Theory Summary
    # ──────────────────────────────────────────────────
    print("""
┌─────────────────────────────────────────────────────────────────────────┐
│  ICEC コピー数の理論的構造 (Supplemental Material, Theorem S.10)         │
├─────────────────────────────────────────────────────────────────────────┤
│                                                                         │
│  Layer 1: 触媒準備 (Lemma S.16 → S.17)                                  │
│    ρ^{⊗μ_i} → c_i  (2準位触媒)                                         │
│    μ_i ~ 1/|ρ_{ij,min}|²  (最弱コヒーレントモードのボトルネック)            │
│                                                                         │
│  Layer 2: 周辺触媒的増幅 (Lemma S.13)                                    │
│    N^k sets → (k+1)·N^k copies of ρ'                                   │
│                                                                         │
│  Layer 3: 相関触媒変換 (Prop S.23, Theorem S.24)                         │
│    漸近 → 単一ショット (触媒 c は Eq.34 で構成)                           │
│                                                                         │
│  ═══════════════════════════════════════════════════                     │
│  入力コピー:   n = μ · N^k                                              │
│  出力コピー:   m = (k+1) · N^k                                          │
│  変換率:       R = (k+1)/μ → ∞  (k → ∞)                                │
│                                                                         │
│  パラメータ:                                                             │
│    d = dim(ρ) = 2^{n_qubits}    (システムの次元)                         │
│    N = |D(ρ')| の Z-module rank  (独立コヒーレントモード数)                │
│    μ_i = O(1/|ρ_{ij}|²)         (触媒あたりのコピー数)                    │
│    μ = Σ μ_i = N · μ_per        (総触媒準備コピー数)                     │
│    k = 増幅ラウンド数             (自由パラメータ)                         │
│                                                                         │
│  運用量子ビット:                                                         │
│    n_q(system) + N(catalysts) + N(ancillas)                             │
│    = log₂(d) + 2N                                                       │
└─────────────────────────────────────────────────────────────────────────┘
""")

    # ──────────────────────────────────────────────────
    # Part 2: Per-Algorithm Analysis
    # ──────────────────────────────────────────────────

    noise_configs = [
        {'name': 'Dephasing γ=2.0',  'dephasing': 2.0, 'depol': 0.0, 'amp_damp': 0.0},
        {'name': 'Depolarizing p=0.3', 'dephasing': 0.0, 'depol': 0.3, 'amp_damp': 0.0},
        {'name': 'Combined',          'dephasing': 1.0, 'depol': 0.15, 'amp_damp': 0.1},
    ]

    algorithms = [
        ('qDRIFT (Heisenberg)',    3, 'plus'),
        ('QKAN (CHEB-d3)',         2, 'plus'),
        ('Control-Free QPE (VPR)', 4, 'plus'),
        ('Regev Factoring (N=15)', 6, 'random'),
    ]

    all_results = []

    for alg_name, n_qubits, state_type in algorithms:
        rho_ideal = make_ideal_state(n_qubits, state_type)
        results = analyze_algorithm(alg_name, n_qubits, rho_ideal, noise_configs)
        all_results.extend(results)

    # ──────────────────────────────────────────────────
    # Part 3: Display Results
    # ──────────────────────────────────────────────────

    print("─" * 90)
    print(f"{'Algorithm':<25s} {'Noise':<20s} {'n_q':>3s} {'d':>4s} "
          f"{'N':>3s} {'μ/cat':>8s} {'μ_tot':>8s} {'k':>3s} "
          f"{'n(copies)':>12s} {'m(out)':>10s} {'Rate':>8s}")
    print("─" * 90)

    prev_alg = ""
    for r in all_results:
        alg = r['algorithm']
        if alg != prev_alg:
            if prev_alg:
                print()
            prev_alg = alg

        mu_per = r['mu_per_catalyst']
        mu_total = r['mu_total']
        n_input = r['n_input_copies']
        m_output = r['m_output_copies']

        mu_per_str = f"{mu_per:.0f}" if mu_per < 1e8 else f"{mu_per:.1e}"
        mu_tot_str = f"{mu_total:.0f}" if mu_total < 1e8 else f"{mu_total:.1e}"
        n_str = f"{n_input:.0f}" if n_input < 1e8 else f"{n_input:.1e}"
        m_str = f"{m_output:.0f}" if m_output < 1e8 else f"{m_output:.1e}"
        rate_str = f"{r['rate']:.4f}" if r['rate'] < 100 else f"{r['rate']:.1f}"

        print(f"{alg:<25s} {r['noise_name']:<20s} {r['n_system_qubits']:>3d} "
              f"{r['dimension']:>4d} {r['N_catalysts']:>3d} "
              f"{mu_per_str:>8s} {mu_tot_str:>8s} {r['k_rounds']:>3d} "
              f"{n_str:>12s} {m_str:>10s} {rate_str:>8s}")

    # ──────────────────────────────────────────────────
    # Part 4: Qubit Scaling Table
    # ──────────────────────────────────────────────────

    print()
    print("=" * 90)
    print("量子ビット数 vs 必要コピー数 (デフェージング γ=2.0, k=1)")
    print("=" * 90)
    print()
    print(f"{'n_qubits':>8s} {'d=2^n':>8s} {'N_cat':>6s} {'μ/cat':>10s} "
          f"{'μ_total':>10s} {'n_copies':>12s} {'m_out':>10s} {'Rate':>8s} "
          f"{'Ops qubits':>10s}")
    print("─" * 90)

    for n_q in [1, 2, 3, 4, 5, 6, 8, 10, 12, 16, 20]:
        d = 2**n_q
        energies = np.arange(d, dtype=float)

        # Create maximally coherent state (worst case for N)
        rho_ideal = make_ideal_state(n_q, 'plus')
        rho_noisy = apply_dephasing(rho_ideal, 2.0)
        rho_noisy = (rho_noisy + rho_noisy.conj().T) / 2
        rho_noisy /= np.trace(rho_noisy)

        req = compute_full_copy_requirements(d, rho_noisy, rho_ideal, energies, k=1)

        mu_per = req['mu_per_catalyst']
        mu_total = req['mu_total']
        n_input = req['n_input_copies']
        m_output = req['m_output_copies']

        def fmt(x):
            if x < 1e6:
                return f"{x:.0f}"
            elif x < 1e12:
                return f"{x:.2e}"
            else:
                return f"{x:.2e}"

        print(f"{n_q:>8d} {d:>8d} {req['N_catalysts']:>6d} "
              f"{fmt(mu_per):>10s} {fmt(mu_total):>10s} "
              f"{fmt(n_input):>12s} {fmt(m_output):>10s} "
              f"{req['rate']:>8.4f} {req['total_operational_qubits']:>10d}")

    # ──────────────────────────────────────────────────
    # Part 5: Noise Strength Dependence
    # ──────────────────────────────────────────────────

    print()
    print("=" * 90)
    print("ノイズ強度 vs 必要コピー数 (n_qubits=3, d=8, k=1)")
    print("=" * 90)
    print()
    print(f"{'Noise Type':<20s} {'Parameter':>10s} {'|ρ_ij,min|':>12s} "
          f"{'μ/cat':>10s} {'μ_total':>10s} {'n_copies':>12s} {'Rate':>8s}")
    print("─" * 90)

    n_q = 3
    d = 2**n_q
    energies = np.arange(d, dtype=float)
    rho_ideal = make_ideal_state(n_q, 'plus')

    # Dephasing sweep
    for gamma in [0.1, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0]:
        rho_noisy = apply_dephasing(rho_ideal, gamma)
        rho_noisy = (rho_noisy + rho_noisy.conj().T) / 2
        rho_noisy /= np.trace(rho_noisy)

        req = compute_full_copy_requirements(d, rho_noisy, rho_ideal, energies, k=1)
        min_c = req['min_nonzero_coherence']

        def fmt(x):
            if x < 1e6: return f"{x:.0f}"
            else: return f"{x:.2e}"

        print(f"{'Dephasing':<20s} {'γ='+str(gamma):>10s} {min_c:>12.2e} "
              f"{fmt(req['mu_per_catalyst']):>10s} {fmt(req['mu_total']):>10s} "
              f"{fmt(req['n_input_copies']):>12s} {req['rate']:>8.4f}")

    print()

    # Depolarizing sweep
    for p in [0.01, 0.05, 0.1, 0.3, 0.5, 0.7, 0.9, 0.99]:
        rho_noisy = apply_depolarizing(rho_ideal, p)

        req = compute_full_copy_requirements(d, rho_noisy, rho_ideal, energies, k=1)
        min_c = req['min_nonzero_coherence']

        def fmt(x):
            if x < 1e6: return f"{x:.0f}"
            else: return f"{x:.2e}"

        print(f"{'Depolarizing':<20s} {'p='+str(p):>10s} {min_c:>12.2e} "
              f"{fmt(req['mu_per_catalyst']):>10s} {fmt(req['mu_total']):>10s} "
              f"{fmt(req['n_input_copies']):>12s} {req['rate']:>8.4f}")

    # ──────────────────────────────────────────────────
    # Part 6: k-dependence (rate improvement)
    # ──────────────────────────────────────────────────

    print()
    print("=" * 90)
    print("増幅ラウンド k vs 変換率 (n_qubits=3, d=8, dephasing γ=2.0)")
    print("=" * 90)
    print()
    print(f"{'k':>4s} {'n_input':>14s} {'m_output':>14s} {'Rate (m/n)':>12s} "
          f"{'Total qubits':>14s} {'EC gates':>14s}")
    print("─" * 75)

    rho_noisy = apply_dephasing(rho_ideal, 2.0)
    rho_noisy = (rho_noisy + rho_noisy.conj().T) / 2
    rho_noisy /= np.trace(rho_noisy)

    N = compute_N_catalysts(rho_ideal, energies)
    mu_per = compute_mu_per_catalyst(rho_noisy, energies)
    mu_total = N * mu_per

    for k in [1, 2, 3, 5, 10, 20, 50, 100]:
        n_input = mu_total * (N ** k)
        m_output = (k + 1) * (N ** k)
        rate = m_output / n_input if n_input > 0 else 0

        # EC gate count: O(k · N^k · N · d²)
        ec_gates = k * (N ** k) * N * (d ** 2)

        # Total qubits: system + copies + catalysts + ancillas
        # In circuit model: log2(d) + N + N (ancillas)
        total_q = int(ceil(log2(d))) + 2 * N

        def fmt(x):
            if x < 1e6: return f"{x:.0f}"
            elif x < 1e15: return f"{x:.2e}"
            else: return f"{x:.2e}"

        print(f"{k:>4d} {fmt(n_input):>14s} {fmt(m_output):>14s} "
              f"{rate:>12.4f} {total_q:>14d} {fmt(ec_gates):>14s}")

    # ──────────────────────────────────────────────────
    # Part 7: Summary for the 4 benchmark algorithms
    # ──────────────────────────────────────────────────

    print()
    print("=" * 90)
    print("4アルゴリズムの必要コピー数まとめ (k=1, dephasing γ=2.0)")
    print("=" * 90)
    print()

    summary_data = []
    for alg_name, n_q, state_type in algorithms:
        d = 2**n_q
        energies = np.arange(d, dtype=float)
        rho_ideal = make_ideal_state(n_q, state_type)
        rho_noisy = apply_dephasing(rho_ideal, 2.0)
        rho_noisy = (rho_noisy + rho_noisy.conj().T) / 2
        rho_noisy /= np.trace(rho_noisy)

        req = compute_full_copy_requirements(d, rho_noisy, rho_ideal, energies, k=1)
        summary_data.append((alg_name, n_q, req))

    print(f"{'Algorithm':<25s} {'n_q':>4s} {'d':>5s} {'N':>4s} "
          f"{'μ/cat':>10s} {'μ_total':>10s} {'Copies(n)':>12s} "
          f"{'Ops qubits':>10s} {'|ρ_min|':>10s}")
    print("─" * 95)

    for alg_name, n_q, req in summary_data:
        def fmt(x):
            if x < 1e6: return f"{x:.0f}"
            else: return f"{x:.2e}"

        print(f"{alg_name:<25s} {n_q:>4d} {req['dimension']:>5d} "
              f"{req['N_catalysts']:>4d} "
              f"{fmt(req['mu_per_catalyst']):>10s} "
              f"{fmt(req['mu_total']):>10s} "
              f"{fmt(req['n_input_copies']):>12s} "
              f"{req['total_operational_qubits']:>10d} "
              f"{req['min_nonzero_coherence']:>10.2e}")

    print()
    print("─" * 95)
    print()
    print("Key:")
    print("  n_q        = システム量子ビット数")
    print("  d          = ヒルベルト空間次元 = 2^{n_q}")
    print("  N          = 2準位触媒の数 (D(ρ') の Z-module rank)")
    print("  μ/cat      = 触媒1個あたりのコピー数 ~ 1/|ρ_{ij,min}|²")
    print("  μ_total    = 全触媒準備コピー数 = N · μ/cat")
    print("  Copies(n)  = 総入力コピー数 = μ_total · N^k")
    print("  Ops qubits = 運用量子ビット数 = n_q + 2N")
    print("  |ρ_min|    = ノイズ後の最弱コヒーレンス (ボトルネック)")
    print()
    print("スケーリング則:")
    print("  n(copies) = O(N^{k+1} / |ρ_{ij,min}|²)")
    print("  N = O(n_q)  [等間隔エネルギーの場合: N = n_q - 1]")
    print("  |ρ_{ij,min}| ~ exp(-γ)/d  [デフェージング後]")
    print("  → n(copies) ~ d² · exp(2γ) · N^{k+1}")
    print("  → コヒーレンスが弱いほど指数的にコピー数が増大")
    print("  → しかし k を増やすと変換率 (k+1)/μ → ∞ なので漸近的に効率的")


if __name__ == '__main__':
    run_full_analysis()
